# Generated by Django 3.0.8 on 2020-07-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='temperature',
            field=models.FloatField(default=36.1),
        ),
    ]
