# Generated by Django 3.0.8 on 2020-07-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_auto_20200721_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
