# Generated by Django 3.0.8 on 2020-07-22 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_visitor_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Centro Comercial',
                'verbose_name_plural': 'Centros Comerciales',
            },
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='date_visited',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='temperature',
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=36.1)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('mall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.Mall')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.Visitor')),
            ],
            options={
                'verbose_name': 'Visitante',
            },
        ),
    ]
