# Generated by Django 3.0.8 on 2020-07-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0004_auto_20200722_0111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registry',
            options={'verbose_name': 'Visita'},
        ),
        migrations.RemoveField(
            model_name='registry',
            name='mall',
        ),
        migrations.AddField(
            model_name='registry',
            name='mall',
            field=models.ManyToManyField(to='api_v1.Mall'),
        ),
    ]
